version: '2'
services:
  app:
    build: .
    restart: always
    ports:
      - 80:3001
      - 443:3001
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
volumes:
  launch_team:
    external:
      name: go-chat-api
